[package]
name = "bin"
version = "0.1.0"
edition = "2021"
authors = ["Matteo Possamai"]
publish = ["kellnr"]

[dependencies]
saver_bot = {path = "../"}
robotics_lib = { version = "0.1.21", registry = "kellnr"  }
oxagaudiotool = { version = "0.1.0", registry = "kellnr"  }
recycle_by_ifrustrati = { version = "0.1.0", registry = "kellnr"  }
asfalt_inator = { version = "0.1.0", registry = "kellnr"  }
charting_tools = { version = "1.0.0", registry = "kellnr"  }
